### ISSUE TITLE
What is the standard way to drop or delete a vertex or edge using neo4j-gremlin-bolt?

### ISSUE THREAD

**Issue by octetful** [SteelBridgeLabs/neo4j-gremlin-bolt#101]
Usually in standard tinkerpop documentation, there is a traversal step called drop mentioned as:
`g.V().drop()`

What is the standard way to drop or delete vertices or edges using the neo4j-gremlin-bolt library?

**Comment by rjbaucells** [comment]
If you have an instance of Vertex you just invoke `vertex.remove()`, that will remove the vertex from the database on commit.
