### ISSUE TITLE
the version problem 

### ISSUE THREAD

**Issue by heyanxian** [SteelBridgeLabs/neo4j-gremlin-bolt#103]
the command :
docker run -d --name neo4j -p 7687:7687 -p 7474:7474 -e NEO4J_AUTH=neo4j/neo4j123 -e NEO4J_ACCEPT_LICENSE_AGREEMENT=yes neo4j:3.4-enterprise
neo4j version are not compatible， you should use  neo4j:3.5.22 version . 
docker run -d --name neo4j -p 7687:7687 -p 7474:7474 -e NEO4J_AUTH=neo4j/neo4j123 -e NEO4J_ACCEPT_LICENSE_AGREEMENT=yes neo4j:3.5.22-enterprise

**Comment by rjbaucells** [comment]
Thanks for reporting it. Updated docker image to `neo4j:4.2-enterprise`.
