### ISSUE TITLE
[Neo4j] Query Sparql against Neo4j repository cost too much traversal time 

### ISSUE THREAD

**Issue by thsohn17** [SteelBridgeLabs/neo4j-gremlin-bolt#108]
Hello ,

i am using neo4j-gremlin-bolt to develop service to query neo4j that is huge amount of data which contains approximately 400,000,000 number of nodes.
the problem is sparql-gremlin SPARQL query works like magic on small size of data like may be 2,000 number of nodes, but not in case of huge size of data as i mentioned above. 

can you give me any idea about that?

thanks

**Comment by rjbaucells** [comment]
This library does not support the gremlin traversals when the number of nodes is huge, data is retrieved to the client and then `gremlin` processed. See other issues already reported.
