### ISSUE TITLE
IdProvinder should support not only from the property

### ISSUE THREAD

**Issue by caivega** [SteelBridgeLabs/neo4j-gremlin-bolt#39]
In Neo4j bold library, the returned Node, org.neo4j.driver.internal.InternalNode has it's id which wasn't in the properties, should have a provider which has a interface like,

T processIdentifier(Vertex node);

I just gremlin traversal the neo4j database.

**Comment by rjbaucells** [comment]
Yes, it is possible to have a provider that uses the native id supplied by the database. I will add it as a feature request for next versions

**Comment by caivega** [comment]
here, https://github.com/caivega/neo4j-gremlin-bolt/commit/8cc41bda2d90cd7ff991a488479d36dce0d809ae, for reference, i just meet my requirement, for traversal, check and see.

**Comment by rjbaucells** [comment]
This enhancement has been completed, use version 0.2.10.
