### ISSUE TITLE
Query: Does this extend support for TinkerPop Python?

### ISSUE THREAD

**Issue by SrinathG910** [SteelBridgeLabs/neo4j-gremlin-bolt#71]
Query: Does this extend support for TinkerPop Python?

_(didnt find any other place to put up a comment/query)_

**Comment by rjbaucells** [comment]
Nope, this is a Java implementation

**Comment by WolfgangFahl** [comment]
https://stackoverflow.com/a/47856088/1497139 states it would be  possible to integrate but it looks like nobody published an example yet.
