### ISSUE TITLE
Variables and Meta properties aren't supported

### ISSUE THREAD

**Issue by anandp504** [SteelBridgeLabs/neo4j-gremlin-bolt#72]
We were using embedded Neo4J in our application and wanted to move to using the bolt interface to access the Neo4J database. I noticed that the variables and meta properties aren't supported and they are explicitly set to false [here](https://github.com/SteelBridgeLabs/neo4j-gremlin-bolt/blob/master/src/main/java/com/steelbridgelabs/oss/neo4j/structure/Neo4JGraphFeatures.java). Can you please suggest how do we make use of variables and meta properties?

```> GraphFeatures
>-- Transactions: true
>-- Computer: false
>-- Persistence: true
>-- ConcurrentAccess: true
>-- ThreadedTransactions: false
> VariableFeatures
>-- Variables: false
>-- BooleanValues: false
>-- ByteValues: false
>-- DoubleValues: false
>-- FloatValues: false
>-- IntegerValues: false
>-- LongValues: false
>-- MapValues: false
>-- MixedListValues: false
>-- SerializableValues: false
>-- StringValues: false
>-- UniformListValues: false
>-- BooleanArrayValues: false
>-- ByteArrayValues: false
>-- DoubleArrayValues: false
>-- FloatArrayValues: false
>-- IntegerArrayValues: false
>-- LongArrayValues: false
>-- StringArrayValues: false
> VertexFeatures
>-- MetaProperties: false
>-- AddVertices: true
>-- RemoveVertices: true
>-- MultiProperties: false
```

**Comment by rjbaucells** [comment]
They are explicitly set as false since the library does not support them.
