### ISSUE TITLE
Unable to get connection from connection pool

### ISSUE THREAD

**Issue by smitapadhy** [SteelBridgeLabs/neo4j-gremlin-bolt#73]
Hi 
  I am new to neo4j and gremling. We have a requirement to connect to a remote neo4j instance from spring boot application.

Neo4JElementIdProvider<?> vertexIdProvider = new Neo4JNativeElementIdProvider();
		Neo4JElementIdProvider<?> edgeIdProvider = new Neo4JNativeElementIdProvider();
		
		graph = new Neo4JGraph(getDriver(), vertexIdProvider, edgeIdProvider);

I am using above code to get instance of graph and various traversals to get the data. Once the data is fetched the graph is closed. 

graph.close();

For each query to db , new graph instance is created and closed. There are no leaking sessions as well.

However , after a few days, we get - "Unable to get connection from connection pool" error. i have tried increasing the max pool size in the driver but it hasnt helped. Since the application is in development phase there arent many users. I am not sure where the connections are getting consumed.

**Comment by rjbaucells** [comment]
This is the recommended way of using the library:
```
    // create graph instance
    try (Graph graph = new Neo4JGraph(driver, vertexIdProvider, edgeIdProvider)) {
        // begin transaction
        try (Transaction transaction = graph.tx()) {
            // use Graph API to create, update and delete Vertices and Edges
            
            // commit transaction
            transaction.commit();
        }
    }
```
I have code in production for more than two years without any problem. 

Now the connection pool is not related to this library, it is managed by the underlying [BOLT](https://github.com/neo4j/neo4j-java-driver) implementation. Make sure the call to `getDriver()` is not creating a driver instance every time you call it, the leak should be there.

**Comment by smitapadhy** [comment]
Thanks Rogelio. the getDriver only creates one instance. That is being used for all the  subsequent calls. I have also enabled leak logging etc but there is no leaking sessions.

**Comment by rjbaucells** [comment]
I am closing this issue since it is not related to this library. Please reopen it if you find anything else...
